In [ ]:
# Cristian Zapata

# Modelo de KNN

In [1]:
# Librerias 

import os
import numpy as np
import pandas as pd
import numpy as np, pandas as pd
import matplotlib.pyplot as plt

Input Variable:

 

**Buying price** (vhigh, high, med, low)

 

**Price of the maintenance** (vhigh, high, med, low)

 

**Number of doors** (2, 3, 4, 5more)

 

**Persons capacity in terms of persons to carry** (2, 4, more)

 

**Size of luggage boot** (small, med, big)

 

**Estimated safety of the car** (low, med, high)

 

Output Variable:

 

**Car acceptability** (unacc, acc, good, vgood)

In [23]:
data = pd.read_csv(r'data/car.data',names=['buying','maint','doors','persons','lug_boot','safety','class'])

In [24]:
data

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:

# Ejercicio 1

'''
Explore el conjunto de datos 

- Revise las primeras 5 obervaciones 
- Identifque el tipo de variable de cada columna 
- Tome un momento para pensar en el contexto general del caso de uso.

'''

In [25]:
print(data.head(5))

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [26]:
data.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
class       object
dtype: object

**Categorizar las variables** 

In [27]:
data['class'] = [1 if valor=='unacc' else 
                 2 if valor=='acc'   else 
                 3 if valor=='good'  else 
                 4 for valor in  data['class']]

In [17]:
print(class_names)
print(data['class'].unique())

Index(['unacc', 'acc', 'vgood', 'good'], dtype='object')
[1 2 4 3]


In [ ]:
# Ejercicio 2 

'''
Dado el ejemplo anterior de categorización de variables, aplique el mismo procedimiento a las columnas pertinentes.
'''

''' Revise que todas las columnas hayan quedado en el tipo de dato deseado'''

In [28]:
for column in data.columns:
    print(column, data[column].unique())

buying ['vhigh' 'high' 'med' 'low']
maint ['vhigh' 'high' 'med' 'low']
doors ['2' '3' '4' '5more']
persons ['2' '4' 'more']
lug_boot ['small' 'med' 'big']
safety ['low' 'med' 'high']
class [1 2 4 3]


In [29]:
data = pd.read_csv(r'data/car.data',names=['buying','maint','doors','persons','lug_boot','safety','class'])

In [30]:
data['class'] = [1 if valor=='unacc' else 
                 2 if valor=='acc'   else 
                 3 if valor=='good'  else 
                 4 for valor in  data['class']]

 

data['safety'] = [1 if valor=='low' else 
                 2 if valor=='med'   else 
                 3 for valor in  data['safety']]

 

data['lug_boot'] = [1 if valor=='small' else 
                 2 if valor=='med'   else 
                 3 for valor in  data['lug_boot']]

 

data['persons'] = [1 if valor=='2' else 
                 2 if valor=='4'   else 
                 3 for valor in  data['persons']]

 

data['doors'] = [1 if valor=='2' else 
                 2 if valor=='3'   else 
                 3 if valor=='4'  else 
                 4 for valor in  data['doors']]

 

data['maint'] = [1 if valor=='low' else 
                 2 if valor=='med'   else 
                 3 if valor=='high'  else 
                 4 for valor in  data['maint']]

 

data['buying'] = [1 if valor=='low' else 
                 2 if valor=='med'   else 
                 3 if valor=='high'  else 
                 4 for valor in  data['buying']]

 

for column in data.columns:
    print(column, data[column].unique())

buying [4 3 2 1]
maint [4 3 2 1]
doors [1 2 3 4]
persons [1 2 3]
lug_boot [1 2 3]
safety [1 2 3]
class [1 2 4 3]


In [31]:
for columns in data.columns:
    print(data[column].unique())

[1 2 4 3]
[1 2 4 3]
[1 2 4 3]
[1 2 4 3]
[1 2 4 3]
[1 2 4 3]
[1 2 4 3]


In [32]:
data

buying  maint  doors  persons  lug_boot  safety  class
0          4      4      1        1         1       1      1
1          4      4      1        1         1       2      1
2          4      4      1        1         1       3      1
3          4      4      1        1         2       1      1
4          4      4      1        1         2       2      1
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      4        3         2       2      3
1724       1      1      4        3         2       3      4
1725       1      1      4        3         3       1      1
1726       1      1      4        3         3       2      3
1727       1      1      4        3         3       3      4

[1728 rows x 7 columns]

In [ ]:
# Ejercicio 3 

'''
Separe las variables predictoras en un objeto llamado X y la variable predictora en y
'''

'''
Realice la construcción del train test split
utilizando la funcion:
from sklearn.model_selection import train_test_split
'''

In [34]:
# Solución
from sklearn.model_selection import train_test_split


# - Separación de variables 
X = data[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']]
y = data['class']

# - Train - test - split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)


In [35]:
print(X_test.shape)
print(X_train.shape)

(519, 6)
(1209, 6)


In [ ]:
# Ejercicio 4

'''
Cargue la función KNeigborsClassifier 
from sklearn.neighbors import KNeighborsClassifier
y cree un modelo de 10 con 10 n_neighbors 
'''

'''
Ajuste los datos de entrenamiento al modelo generado en el literal anterior 
'''

In [36]:
#####

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
 

knn = KNeighborsClassifier(n_neighbors=10)

 

modelo_knn = knn.fit(X_train,y_train)

 

#### Predicciones

 

predicciones = modelo_knn.predict(X_test)

 

#### Evaluación

 

print(classification_report(y_test, predicciones)) 

              precision    recall  f1-score   support

           1       0.92      1.00      0.96       356
           2       0.90      0.82      0.86       121
           3       0.82      0.36      0.50        25
           4       1.00      0.71      0.83        17

    accuracy                           0.92       519
   macro avg       0.91      0.72      0.79       519
weighted avg       0.91      0.92      0.91       519



In [ ]:
# Ejercico 5

'''
en una variable llamada predicciones determine la predicción del modelo para los valores de prueba
'''

'''
Calcule el accuracy del modelo con la función 
from sklearn.metrics import accuracy_score 
'''

'''Utilice la asignación de predicciones del literal primero para evaluar el classification report
con la función:
from sklearn.metrics import classification_report
'''

**Forma de determinar el n_neighbors mas adecuado** 

In [37]:
from sklearn.metrics import accuracy_score
for K in range(25):
    K_value = K+1
    neigh = KNeighborsClassifier(n_neighbors = K_value)
    neigh.fit(X_train, y_train)
    y_pred = neigh.predict(X_test)
    print("Accuracy is ", accuracy_score(y_test,y_pred)*100,"% for K-Value:",K_value)

Accuracy is  84.20038535645472 % for K-Value: 1
Accuracy is  80.92485549132948 % for K-Value: 2
Accuracy is  89.40269749518305 % for K-Value: 3
Accuracy is  89.01734104046243 % for K-Value: 4
Accuracy is  93.83429672447014 % for K-Value: 5
Accuracy is  93.0635838150289 % for K-Value: 6
Accuracy is  93.0635838150289 % for K-Value: 7
Accuracy is  92.29287090558766 % for K-Value: 8
Accuracy is  92.10019267822736 % for K-Value: 9
Accuracy is  91.71483622350675 % for K-Value: 10
Accuracy is  90.36608863198458 % for K-Value: 11
Accuracy is  89.98073217726397 % for K-Value: 12
Accuracy is  90.5587668593449 % for K-Value: 13
Accuracy is  90.5587668593449 % for K-Value: 14
Accuracy is  90.17341040462428 % for K-Value: 15
Accuracy is  90.5587668593449 % for K-Value: 16
Accuracy is  90.7514450867052 % for K-Value: 17
Accuracy is  90.17341040462428 % for K-Value: 18
Accuracy is  89.78805394990366 % for K-Value: 19
Accuracy is  89.21001926782274 % for K-Value: 20
Accuracy is  89.78805394990366 % fo